---
name: Build Docker Image

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          build-args: BRANCH=${{ github.ref_name }}
          context: "."
          push: true
          tags: ghcr.io/anthrocon-rams/anthrocon:${{ github.ref_name }}